jorenn92/Maintainerr

ui/src/components/Layout/index.tsx
When opening the UI, don't show the navbar on mobile.
=> fix(ui): hide navbar on initial load

ui/src/components/Layout/index.tsx
After the tailwind 3.1.0 upgrade, the searchbar appears too wide after a production build.
=> fix(ui): searchbar too wide after latest tailwind update

ui/src/components/Common/CommunityRuleModal/index.tsx, ui/src/components/Rules/Rule/RuleCreator/CommunityRuleUpload/index.tsx
Closes the modal after a rule upload. This way we force to user to refetch all rules when reopening the modal.
=> fix(community rules): Close modal after upload

supervisord.conf
This allows us to mount the root filesystem as read-only. 
[See here: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/](https://kubesec.io/basics/containers-securitycontext-readonlyrootfilesystem-true/)
=> fix: do not create a supervisord.log file

Dockerfile
Node appears to want to access /opt/app/.cache, but when running as non-default user the /opt/app isn't writable. We attempted to create a more permissive directory during build to accommodate this but the location was slightly wrong.
I can reproduce the issue by running `podman run -u 1001:1001 docker.io/jorenn92/maintainerr:latest`, which gives me a constantly respawning daemon and logs like this:
```
2024-02-04 12:42:18,185 INFO supervisord started with pid 1
2024-02-04 12:42:19,188 INFO spawned: 'docs' with pid 2
2024-02-04 12:42:19,189 INFO spawned: 'server' with pid 3
2024-02-04 12:42:19,191 INFO spawned: 'ui' with pid 4
Internal Error: EACCES: permission denied, mkdir '/opt/app/.cache'
Error: EACCES: permission denied, mkdir '/opt/app/.cache'
2024-02-04 12:42:19,595 WARN exited: …
```
=> fix(docker): create .cache directory in expected location

package.json, ui/src/components/Settings/Overseerr/index.tsx, ui/src/components/Settings/Radarr/index.tsx, ui/src/components/Settings/Sonarr/index.tsx, ui/src/utils/SettingsUtils.ts, yarn.lock
Previously, when a path was included in the hostname, the port portion of the URL would be incorrectly appended at the end, resulting in URLs like "http(s)://hostname/pathname:port". This fix ensures that URLs are generated correctly.
=> 976 977 993 fix configuration port with custom path

ui/src/components/Settings/Overseerr/index.tsx, ui/src/components/Settings/Radarr/index.tsx, ui/src/components/Settings/Sonarr/index.tsx
This took me way too long to figure out. Hence this PR to fix this for future me (And everyone else).
Because the fields are labeled as Hostname / IP it wasn't clear you could enter https://hostname in that field (Which technically is a URL, not a hostname).
So I put my hostname and port 443 in the settings, but every time I clicked test it failed.
It wasn't untill I refreshed the page it became clear the hostname was prepended with http:// by default.
This PR fixes this by prepending the hostname with https when using port 443, or http if not.
The includes checks could be combined into one (https always contains http, so no need to check twice), and I've added a condition for port 443.
(First PR here, please let me know if anything is missing)
=> fix: Automatically prepend https for Overseerr, Sonarr and Radarr when using port 443

.vscode/settings.json, README.md, server/src/app/app.module.ts, server/src/database/migrations/1727097172777-Add_Tautulli_settings.ts, server/src/modules/api/lib/cache.ts, server/src/modules/api/tautulli-api/helpers/tautulli-api.helper.ts, server/src/modules/api/tautulli-api/tautulli-api.controller.ts, server/src/modules/api/tautulli-api/tautulli-api.module.ts, server/src/modules/api/tautulli-api/tautulli-api.service.ts, server/src/modules/collections/collections.module.ts, server/src/modules/rules/constants/rules.constants.ts, server/src/modules/rules/getter/getter.service.ts, server/src/modules/rules/getter/tautulli-getter.service.ts, server/src/modules/rules/rules.module.ts, server/src/modules/rules/rules.service.ts, server/src/modules/settings/dto's/setting.dto.ts, server/src/modules/settings/entities/settings.entities.ts, server/src/modules/settings/settings.controller.ts, server/src/modules/settings/settings.module.ts, server/src/modules/settings/settings.service.ts, ui/src/components/Settings/Plex/index.tsx, ui/src/components/Settings/Radarr/index.tsx, ui/src/components/Settings/Sonarr/index.tsx, ui/src/components/Settings/Tautulli/index.tsx, ui/src/components/Settings/index.tsx, ui/src/contexts/settings-context.tsx, ui/src/pages/settings/tautulli/index.tsx
Currently a WIP to get some early feedback and to collect ideas on the type of rules you'd like to see. This currently implements **seen by** like Plex, but uses Tautulli's own watched logic.
[Originally](https://discord.com/channels/1152219249549512724/1152219250291920929/1287717659013550080) I was thinking the percentage watched could be controlled as part of the rule, but this doesn't seem possible the way the rule system works with lists? I'd want to do '[list] requested in Overseerr' contains '[list] watched in Tautulli' where watched percentage above 90.
Anyway, it turns out Tautulli already has it's own settings for this which controls the watched_status in their history response. I think this might be sufficient enough for most use cases?:
One improvement I'd like to make on this …
=> Add Tautulli integration

server/src/modules/api/tautulli-api/tautulli-api.service.ts, server/src/modules/rules/getter/tautulli-getter.service.ts
get_item_watch_time_stats returns all views regardless of the watched percentage which was not the intention.
=> fix: Tautulli Times viewed & Total views

.github/workflows/stale_issues.yml
Adding a workflow to auto mark issues as stale after 30 days of no activity, then close them after 14 days of being marked stale.
I also added that it will ignore the bug, never-stale, and enhancement labels. It will also ignore the issue if one of (jorenn92,ydkmlt84,benscobie) have been assigned to the issue.
Currently it is marked with debug-only: true for dry-run purposes.
=> auto-stale issues workflow

server/src/database/migrations/1728503476668-Update_tautulli_URL.ts, server/src/modules/api/tautulli-api/tautulli-api.service.ts, ui/src/components/Settings/Radarr/index.tsx, ui/src/components/Settings/Sonarr/index.tsx, ui/src/components/Settings/Tautulli/index.tsx, ui/src/utils/SettingsUtils.ts
Resolves #1305
I've added a migration to trim any trailing slash of the tautulli_url as the hostname logic is now the same as Sonarr & Radarr.
I've also removed the ref usage in favour of state. Was there a particular reason for using both as this seems to be common throughout the code base? I've only ever seen state being used for form inputs, unless using a library such as React Hook Form which uses refs.
=> feat: Add base URL to Tautulli settings

.github/workflows/dependabot_merge.yml
Major changes will sometimes require some code changes. Most of these will be picked up by the build failing but that's not always the case like here: https://github.com/jorenn92/Maintainerr/pull/1340
There's also some merit in holding off using a new major release like https://github.com/jorenn92/Maintainerr/pull/1336 as from experience nextjs is initially pretty unstable.
=> chore: Only auto merge patch & minor version changes

Dockerfile, README.md, server/src/main.ts, server/src/modules/api/internal-api/internal-api.service.ts, supervisord.conf, ui/next.config.js, ui/src/middleware.ts
For feature request: https://features.maintainerr.info/posts/41/pass-in-node-port-as-an-environment-variable-in-docker-compose
We have to use next.js middleware here as next.config.js is build-time config.
=> feat: Add envars to control service ports

.github/workflows/release.yml, .github/workflows/release_pr.yml
Adding the comment `/release-pr` to a PR will build and push it to the Docker registries. The tag it will use is `pr-{prNumber}`, in this PRs case `pr-1359`.
A comment will be added on success/fail:
The workflow is limited to collaborators and the owner.
I've also removed the restriction on the release workflow which will allow me to push releases out. By default only users with write access to the repo can run actions anyway.
At some point I'd like to create a scheduled workflow to remove old PR tags to keep the registry a bit cleaner.
=> chore: Add issue comment workflow to push PRs to Docker repos

.gitattributes, server/src/modules/api/servarr-api/helpers/sonarr.helper.ts, server/src/modules/api/servarr-api/servarr.service.ts, server/src/modules/collections/collection-worker.service.ts
- Ensure that .sh files have LF line endings. Executing a .sh file with CRLF line breaks will not work.
- I broke handling of media in my multi *arr work as I was attempting to check the related radarr & sonarr setting IDs via the child collection. This would never work as you can only have one or none. I'm now checking the setting ID on the collection itself.
- We were logging "Unmonitored x from Sonarr show with ID x" even when the call failed
- Check that the returned Sonarr media has an ID before performing any actions on it. getSeriesByTvdbId() always returns a result for a valid TVDB ID, it's just that the fallback API call we make doesn't return an ID.
- Check that the unmonitoring seasons call worked before attempting to unmonitor the series. An exception could be thrown here …
=> fix: Handling collections & Sonarr media existence check

Dockerfile
Files were owned by node:node with 755. If you override the user then they won't have permission to replace `__PATH_PREFIX__` on startup. This change makes the UI folder writable by anybody. At first I didn't like this, but as it was 755 before then the node user could already write files. Really this is no worse as we're in a container.
=> fix: __PATH_PREFIX__ not replaced when using user directive

README.md, ui/next.config.js, ui/src/components/Rules/RuleGroup/AddModal/index.tsx, ui/src/components/Settings/Overseerr/index.tsx, ui/src/components/Settings/Plex/index.tsx, ui/src/components/Settings/Radarr/SettingsModal/index.tsx, ui/src/components/Settings/Sonarr/SettingsModal/index.tsx, ui/src/components/Settings/Tautulli/index.tsx
With the changes to the docs URL generation, it no longer creates URLs from the directory structure. This started causing problems with redirect errors in the docs. Now all docs links, besides the main URL `docs.maintainerr.info` end with `.html`
All URLs in the project have been corrected to point at the right URL.
=> fix: changed all docs URLs to match new docs URL generations.

server/src/database/migrations/1733357722729-Remove-default-arr-servers.ts, server/src/modules/api/plex-api/plex-api.service.ts, server/src/modules/api/servarr-api/interfaces/radarr.interface.ts, server/src/modules/api/servarr-api/interfaces/sonarr.interface.ts, server/src/modules/collections/collection-worker.service.ts, server/src/modules/rules/constants/rules.constants.ts, server/src/modules/rules/getter/radarr-getter.service.ts, server/src/modules/rules/getter/sonarr-getter.service.ts, server/src/modules/rules/rules.service.ts, server/src/modules/settings/dto's/radarr-setting.dto.ts, server/src/modules/settings/dto's/sonarr-setting.dto.ts, server/src/modules/settings/entities/radarr_settings.entities.ts, server/src/modules/settings/entities/sonarr_settings.entities.ts, server/src/modules/settings/settings.service.ts, ui/src/components/Rules/RuleGroup/AddModal/ArrAction/index.tsx, ui/src/components/Rules/RuleGroup/AddModal/index.tsx, ui/src/components/Settings/Radarr/SettingsModal/index.tsx, ui/src/components/Settings/Radarr/index.tsx, ui/src/components/Settings/Sonarr/SettingsModal/index.tsx, ui/src/components/Settings/Sonarr/index.tsx
For feature request: https://features.maintainerr.info/posts/52/allow-to-filter-based-on-the-original-language-value-in-sonarr
I've fixed the Radarr & Sonarr server selection not persisting on initial rule creation. I've also fixed an exception/logic error when checking the cacheReset flag.
=> feat: Add "Original Language" rule to Sonarr & Radarr

docker/start.sh
For whatever reason the find exec command is hanging for somebody with a Synology DS920+. We tried a bunch of different ways and settled on xargs instead of exec. I've also ignored the node_modules folder to speed up processing.
Discord thread: https://discord.com/channels/1152219249549512724/1318539096813076563
=> fix: Container startup failing for some

server/src/app/app.controller.ts, server/src/modules/collections/collections.controller.ts, server/src/modules/collections/collections.service.ts, server/src/modules/rules/rules.controller.ts, server/src/modules/rules/rules.service.ts, ui/next-env.d.ts, ui/package.json, ui/src/components/Settings/About/Releases/index.tsx, ui/src/components/Settings/About/index.tsx, ui/src/components/Settings/index.tsx, ui/src/pages/settings/about/index.tsx, ui/styles/globals.css, yarn.lock
I somehow messed up the yarn.lock file and needed to reset.
- shows releases and a button to view changelog
- shows total number of rules
- shows version
- total media currently in collections
- number of community rules
- useful links section
- donations section
=> feat: add about page

ui/src/components/Rules/RuleGroup/AddModal/index.tsx
When opening an existing TV Show rule, the media type would be incorrectly set to Shows instead of what was saved.
=> fix: Media type selection not reflecting what is saved

server/src/modules/rules/rules.service.ts, ui/src/components/Rules/RuleGroup/AddModal/index.tsx
Not sure what I was thinking when I added this in. It doesn't make any sense to reset the collection when changing the *arr server, it's similar to changing rule logic which does not trigger a collection reset so why should this.
=> fix: Do not reset collection on *arr server change

server/src/modules/collections/collections.service.ts
The selected Sonarr/Radarr server was not being saved when creating a new rule.
=> fix: *arr server not persisting on initial save

server/src/modules/api/servarr-api/helpers/sonarr.helper.ts, server/src/modules/api/servarr-api/interfaces/sonarr.interface.ts, server/src/modules/rules/constants/rules.constants.ts, server/src/modules/rules/getter/sonarr-getter.service.ts, ui/src/components/Rules/Rule/RuleCreator/RuleInput/index.tsx
Adds two new filters for seasons; **Season has season finale episode** and **Season has series finale episode**.
I have also resolved a client side error when changing rule data/media type, as well as improving & resolving some types.
Resolves feature request: https://features.maintainerr.info/posts/18/add-sonarrs-season-finale-label-as-seasons-rule-filter
=> feat: Add season has season/series finale episode

server/src/modules/rules/constants/rules.constants.ts, server/src/modules/rules/getter/sonarr-getter.service.ts
Adds season number as a filter for Sonarr, as requested in https://features.maintainerr.info/posts/30/selective-season-deletion-for-plex
Dependent on https://github.com/jorenn92/Maintainerr/pull/1471 merging first. Will switch the base branch afterwards.
=> feat: Add season number filter

server/src/modules/rules/helpers/rule.comparator.service.ts, server/src/modules/rules/tests/rule.comparator.service.doRuleAction.spec.ts
- `['abc', 'def']` first value now only matches `['abc', 'def']` second value
- `['abc', 'ghi']` first value will not return true when compared against `['abc', 'def']`
- fixes #1151 
I couldn't think of every case and test everything, but I tried to test a lot of them. Please let me know if it doesn't work somewhere.
This change makes this code from [rule.comparator.service.doRuleAction.spec.ts](https://github.com/jorenn92/Maintainerr/blob/149dc78d08beed8df967e8da576307b8cf02f1ce/server/src/modules/rules/tests/rule.comparator.service.doRuleAction.spec.ts) actually a true statement. 
```
it('should return true when comparing an array of strings with action EQUALS', () => {
const val1 = ['abc', 'def'];
const val2 = ['abc', 'def'];
const action = RulePossibility.EQUALS;
const result = …
```
=> fix: equals comparison action now works to match exact matches only.

.github/workflows/dependabot_merge.yml, server/src/modules/api/plex-api/plex-api.controller.ts
A fresh clone of the repo + `yarn && yarn dev` results in the following error, as `path-to-regexp` is locked to v8.2.0 in `yarn.lock`:
This PR simply fixes the route param to use the new optional syntax.
=> fix: update optional page route param to new syntax

README.md, ui/next.config.js, ui/src/components/Common/DocsButton/index.tsx, ui/src/components/Rules/RuleGroup/AddModal/index.tsx
The versioning for mkdocs creates separate folders inside the gh-pages branch. So that you can switch between different versions. You have to set a default alias that auto-redirects `docs.maintainerr.info/latest` the main URL (`docs.maintainerr.info`). However, this only happens for the base domain. The others still need the `/latest` endpoint.
=> docs url changes again to support docs versioning

server/src/modules/rules/rules.service.ts, ui/src/components/Collection/CollectionItem/index.tsx, ui/src/components/Common/CommunityRowTableRow/index.tsx, ui/src/components/Common/CommunityRuleModal/index.tsx, ui/src/components/Rules/Rule/RuleCreator/CommunityRuleUpload/index.tsx
This PR removes the need for me to self host the community rules, uses a free service (for now) provided by Cloudflare KV, and removes the need to include an API key into the committed code. Adds some automated community rules cleanup as well. There is also a rate limit of 5 per minute to POST or PATCH (new rules or karma) requests to the worker, which will time out for 60 seconds, to avoid spamming.
- Moved the community rules into a Cloudflare Worker/KV flow to remove self-hosted requirement
- Fixed the poster image scroll issue in collection description
- Added an optional "Uploaded by" box to the rule upload
- Added an uploaded by column to the community rule display
- Added uploaded by as search criteria to community rules
- Added a hasRule tag to uploaded rules
- Added a rule …
=> chore: move from self hosted community rules

README.md, server/src/app/app.module.ts, server/src/database/migrations/1740868281450-Add_jellyseerr_settings.ts, server/src/modules/api/jellyseerr-api/helpers/jellyseerr-api.helper.ts, server/src/modules/api/jellyseerr-api/jellyseerr-api.controller.ts, server/src/modules/api/jellyseerr-api/jellyseerr-api.module.ts, server/src/modules/api/jellyseerr-api/jellyseerr-api.service.ts, server/src/modules/api/lib/cache.ts, server/src/modules/collections/collection-worker.service.ts, server/src/modules/collections/collections.module.ts, server/src/modules/rules/constants/rules.constants.ts, server/src/modules/rules/getter/getter.service.ts, server/src/modules/rules/getter/jellyseerr-getter.service.ts, server/src/modules/rules/rules.module.ts, server/src/modules/rules/rules.service.ts, server/src/modules/settings/dto's/setting.dto.ts, server/src/modules/settings/entities/settings.entities.ts, server/src/modules/settings/settings.controller.ts, server/src/modules/settings/settings.module.ts, server/src/modules/settings/settings.service.ts, ui/src/components/Settings/Jellyseerr/index.tsx, ui/src/components/Settings/index.tsx, ui/src/contexts/settings-context.tsx, ui/src/pages/settings/jellyseerr/index.tsx
This is a complete copy of our existing Overseerr code as the APIs we use are functionally the same at the moment. The only feature I have not brought across is the 'Force reset Overseerr record' option, as availability sync should be used instead. If we have problems with this we can always introduce the option again.
Feature request: https://features.maintainerr.info/posts/69/jellyseerr
=> feat: Add Jellyseerr support

.github/pull_request_template.md, CONTRIBUTING.md
This PR updates the contributing guidelines to highlight the importance of discussing large changes as well as keeping PRs focused to one meaningful change. For contributors, this ensures they receive early feedback on their approach, helping to align their work with the project's goals and avoid wasted effort. For reviewers, it provides context and clarity, making the review process more efficient and focused.
I’ve also added a PR template to make it easier for everyone to include the right information in pull requests. It ensures details like the purpose of the change, related issues, and testing steps are clear, making it quicker for reviewers to understand and provide feedback. This also helps prevent important details from being missed.
=> chore: Update contributing doc and add PR template

server/src/modules/rules/constants/constants.service.ts, server/src/modules/rules/constants/rules.constants.ts, server/src/modules/rules/getter/getter.service.ts, server/src/modules/rules/getter/plex-getter.service.ts, server/src/modules/rules/helpers/rule.comparator.service.ts, server/src/modules/rules/tests/rule.comparator.service.doRuleAction.spec.ts, ui/src/components/Rules/Rule/RuleCreator/RuleInput/index.tsx, ui/src/contexts/constants-context.tsx
This PR:
- Creates new rule types, `NUMBER_LIST` and `TEXT_LIST` (I chose "list" to align with the term already used in the UI/copy)
- Adds new rule actions for those rule types - `COUNT_EQUALS`, `COUNT_NOT_EQUALS`, `COUNT_BIGGER`, `COUNT_SMALLER`
- Moves the existing rule possibilities/actions that were only applicable to lists from `NUMBER` and `TEXT` to the new rule types
- Updates all existing rules that are lists to use the new RuleType
- Adds tests, updates the frontend, etc to accommodate for the new rule type
- Also does a small amount of cleanup of types, which was so I could make sure that I wasn't accidentally missing any cases when updating `doRuleAction` to support the new potential value types. I want to do a lot more cleanup here, but I'll do that in its own refactoring PR …
=> feat: allow comparing list sizes against a number

server/src/modules/api/jellyseerr-api/jellyseerr-api.service.ts, server/src/modules/rules/constants/rules.constants.ts, server/src/modules/rules/getter/jellyseerr-getter.service.ts
Adds the ability for Jellfin users signing into Jellyseerr to be matched in rules.
Resolves #1658
=> feat: allow jellyfin users in jellyseerr integration

server/src/modules/collections/collection-handler.spec.ts, server/src/modules/collections/collection-handler.ts
I spotted `plexData` wasn't being set whilst refactoring, another L for having strict disabled. This bug was introduced in [this commit](https://github.com/jorenn92/Maintainerr/pull/1659/files#diff-05876c881d79d411f925e4a5d613de143512ef618b0c272a0bfdab66667b932bL255-L269), has not made it into a release yet.
=> fix: force reset Overseerr throwing exception

.github/workflows/build.yml, .github/workflows/release.yml
I poo poo'd the Docker image tags and a bunch of badly named ones got pushed (see https://hub.docker.com/r/jorenn92/maintainerr/tags - can we delete these?). I created a temporary branch to re-run just the Docker image build for 2.14.0 after I fixed the workflow.
I've added major and major.minor tags here as well. I like to pin to a major version as upgrading might involve manual steps. I think using `:latest` is a bad idea in most cases.
=> chore(ci): Fix Docker image tags

ui/src/components/Collection/CollectionDetail/TestMediaItem/index.tsx, ui/src/components/Collection/CollectionDetail/index.tsx
I incorrectly refactored to use the collection ID instead of the rule group ID, they are typically aligned but not always. This reverts that specific change.
Please describe the steps to test your changes, including any setup required.
1. Use Test Media and validate the result
=> fix: Test media targeting the wrong rule group

server/src/modules/settings/settings.service.ts
When updating Tautulli settings, the in-memory values were not being updated and the API client was not re-built. This meant that any calls (excluding the Test endpoint) to the Tautulli API would use the old settings, which could be empty on a fresh install.
1. Empty your Tautulli settings out
2. Restart the app
3. Add Tautulli settings
4. Add a Tautulli rule group
5. Run rules and check that everything worked ok
=> fix: Tautulli settings not updating until restart

ui/src/components/Common/MediaCard/MediaModal/index.tsx, ui/src/components/Settings/Logs/index.tsx, ui/src/contexts/events-context.tsx
This PR addresses inconsistencies in how `basePath` is handled across the Maintainerr frontend.
Following the discussion in [#1562](https://github.com/jorenn92/Maintainerr/pull/1562#issuecomment-2917398495), I identified several places where the `basePath` was not respected, causing issues when the app is hosted under a subpath (e.g., `/maintainerr`):
* Some static assets in the Media modal (e.g., rating icons) were using absolute paths (`/`) without prepending the `basePath`.
* Both `ReconnectingEventSource` instances (for `/api/events/stream` and `/api/logs/stream`) were also using hardcoded paths, resulting in repeated 404 errors in the browser console when running Maintainerr under a custom `BASE_PATH`.
These issues are now resolved by ensuring all asset and API paths correctly …
=> fix: prepend missing basePath occurences

server/src/modules/rules/helpers/rule.comparator.service.ts
I feel like I'm playing whac-a-mole with statistics bugs.
A rule that looked like this: `AND(2 rules), OR(1 rule), AND(1 rule)` would result in the section 3 (id: 2) operator being `OR` instead of `AND` in metadata / test media **(the actual logic is fine)**. I've removed the block that was causing the issue, there's other code that already handles setting the operator correctly.
I have also removed the operator from the first rule in the ruleResults as it has no effect on the end result, we're leaking an implementation detail there really.
Was introduced in #1777 when I was fixing a different bug.
1. Create a rule group that looks like the example above
2. Run rules
3. Validate the first couple of additions metadata is correct
=> fix: Incorrect sectionResults operator
